"""social: friendships + live friend duels

Revision ID: 5c402b74891e
Revises: e7f8a9b0c1d2
Create Date: 2026-06-25 05:16:21.079733

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5c402b74891e"
down_revision: str | Sequence[str] | None = "e7f8a9b0c1d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friend_duels",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("challenger_id", sa.Uuid(), nullable=False),
        sa.Column("opponent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("round_set", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("server_answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("current_round", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "challenger_round_wins", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("opponent_round_wins", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("winner_side", sa.String(length=16), nullable=True),
        sa.Column("result_reason", sa.String(length=32), nullable=True),
        sa.Column("contest_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["challenger_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["opponent_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_friend_duels_challenger_id"), "friend_duels", ["challenger_id"], unique=False
    )
    op.create_index(
        op.f("ix_friend_duels_opponent_id"), "friend_duels", ["opponent_id"], unique=False
    )
    op.create_table(
        "friendships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("addressee_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["addressee_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requester_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("requester_id", "addressee_id", name="uq_friendship_pair"),
    )
    op.create_index(
        op.f("ix_friendships_addressee_id"), "friendships", ["addressee_id"], unique=False
    )
    op.create_index(
        op.f("ix_friendships_requester_id"), "friendships", ["requester_id"], unique=False
    )
    op.create_table(
        "friend_duel_rounds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("duel_id", sa.Uuid(), nullable=False),
        sa.Column("round_index", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=12), nullable=False),
        sa.Column("challenger_answer", sa.Integer(), nullable=True),
        sa.Column("challenger_correct", sa.Boolean(), nullable=False),
        sa.Column("challenger_time_ms", sa.Integer(), nullable=False),
        sa.Column("opponent_answer", sa.Integer(), nullable=True),
        sa.Column("opponent_correct", sa.Boolean(), nullable=False),
        sa.Column("opponent_time_ms", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("outcome_reason", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["duel_id"], ["friend_duels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("duel_id", "round_index", name="uq_friend_duel_round_index"),
    )
    op.create_index(
        op.f("ix_friend_duel_rounds_duel_id"), "friend_duel_rounds", ["duel_id"], unique=False
    )
    op.create_table(
        "friend_duel_submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("duel_id", sa.Uuid(), nullable=False),
        sa.Column("round_index", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("answer", sa.Integer(), nullable=True),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("time_ms", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["duel_id"], ["friend_duels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("duel_id", "round_index", "user_id", name="uq_friend_duel_submission"),
    )
    op.create_index(
        op.f("ix_friend_duel_submissions_duel_id"),
        "friend_duel_submissions",
        ["duel_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_friend_duel_submissions_duel_id"), table_name="friend_duel_submissions")
    op.drop_table("friend_duel_submissions")
    op.drop_index(op.f("ix_friend_duel_rounds_duel_id"), table_name="friend_duel_rounds")
    op.drop_table("friend_duel_rounds")
    op.drop_index(op.f("ix_friendships_requester_id"), table_name="friendships")
    op.drop_index(op.f("ix_friendships_addressee_id"), table_name="friendships")
    op.drop_table("friendships")
    op.drop_index(op.f("ix_friend_duels_opponent_id"), table_name="friend_duels")
    op.drop_index(op.f("ix_friend_duels_challenger_id"), table_name="friend_duels")
    op.drop_table("friend_duels")
    # ### end Alembic commands ###
