"""M1: users, profiles, user_themes, coin_ledger

Revision ID: a1fa87f4cd0e
Revises:
Create Date: 2026-06-06 13:11:24.107888

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1fa87f4cd0e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "coin_ledger",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("delta", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("ref_type", sa.String(length=64), nullable=True),
        sa.Column("ref_id", sa.Uuid(), nullable=True),
        sa.Column("balance_after", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_coin_ledger_user_id"), "coin_ledger", ["user_id"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("rating", sa.Integer(), server_default=sa.text("1000"), nullable=False),
        sa.Column("division", sa.String(length=16), nullable=False),
        sa.Column("streak_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_streak_date", sa.Date(), nullable=True),
        sa.Column("sharpness", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("coins_balance", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "equipped_theme",
            sa.String(length=64),
            server_default=sa.text("'daylight'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_profiles_username"), "profiles", ["username"], unique=True)
    op.create_table(
        "user_themes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("theme_id", sa.String(length=64), nullable=False),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "theme_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_themes")
    op.drop_index(op.f("ix_profiles_username"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_coin_ledger_user_id"), table_name="coin_ledger")
    op.drop_table("coin_ledger")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
