"""Third-party sign-in: user_identities, and users.password_hash becomes nullable

Sign in with Apple / Google. Two changes, and the second is the one worth reading twice.

`user_identities` keys on (provider, subject) — the provider's immutable user id, not the email.
An email can be changed at Apple or Google without telling us, and Apple's Hide My Email hands us a
relay address that is not the player's at all. Keying on the subject keeps an account attached
through both; keying on email would silently orphan it.

`users.password_hash` becomes NULLABLE because an account created by tapping a provider button has
no password of ours to store. That is the security benefit, not a gap: we never receive the player's
Apple or Google credential, so there is nothing about them for an attacker to take from us.

Hand-written rather than autogenerated. Autogenerate on this schema routinely proposes unrelated
drops, and a migration that touches the users table is the last place to accept that.

Reversible: downgrade drops the identities table and restores NOT NULL. It backfills an unusable
placeholder hash first, because rows created by social sign-in have no password and the constraint
cannot be restored while they hold NULL. That value is an argon2-shaped string that no password can
produce, so those accounts remain unreachable by password rather than becoming reachable by a known
one — a downgrade must not open a door.

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "b2c3d4e5f6a7"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None

# Not a hash of anything. argon2 verification against this fails for every input, so a downgraded
# social account stays password-unreachable instead of being handed a guessable credential.
_UNUSABLE_PASSWORD = "!social-no-password"


def upgrade() -> None:
    op.create_table(
        "user_identities",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        # Apple sends the email on the FIRST authorization only, so later rows legitimately have
        # none. Nullable is correct here, not laziness.
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint("provider", "subject", name="uq_user_identities_provider_subject"),
    )
    op.create_index("ix_user_identities_user_id", "user_identities", ["user_id"])

    op.alter_column("users", "password_hash", existing_type=sa.String(), nullable=True)


def downgrade() -> None:
    op.execute(
        sa.text("UPDATE users SET password_hash = :ph WHERE password_hash IS NULL").bindparams(
            ph=_UNUSABLE_PASSWORD
        )
    )
    op.alter_column("users", "password_hash", existing_type=sa.String(), nullable=False)
    op.drop_index("ix_user_identities_user_id", table_name="user_identities")
    op.drop_table("user_identities")
