"""oauth_transactions: server-side state for the Sign in with Google code flow

One row per in-flight sign-in round trip. It exists so that both single-use gates in the flow are
enforceable by the DATABASE rather than by hope:

  `state`         unique, so the callback can consume it exactly once even if two callbacks race.
  `handoff_code`  unique, so the SPA can trade it for a session exactly once.

A signed, stateless `state` was the alternative and cannot do this: verifying a signature proves we
minted the value, never that we have not already honoured it, so it stays replayable for as long as
it is valid. The row also carries the guest identity resolved from a validated bearer token at
`/start`, which is what lets a guest's coins, streak and rating follow them onto the account instead
of being stranded — and it lives server-side precisely so the client cannot nominate which account a
sign-in attaches to.

Nothing secret is stored. The authorization code is exchanged in the request that receives it and
never persisted; the ID token is verified and discarded. What remains is the outcome.

Hand-written, not autogenerated: autogenerate on this schema routinely proposes unrelated drops.

Reversible: downgrade drops the table outright. It holds only in-flight handshake state with a
ten-minute lifetime, so there is nothing durable to preserve — any sign-in caught mid-flight fails
closed and the player taps the button again.

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "c3d4e5f6a7b8"
down_revision = "b2c3d4e5f6a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "oauth_transactions",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=128), nullable=False),
        sa.Column("nonce", sa.String(length=128), nullable=False),
        # SET NULL, not CASCADE: losing the guest row should not erase the record of the attempt.
        sa.Column(
            "guest_user_id",
            sa.Uuid(),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("handoff_code", sa.String(length=128), nullable=True),
        sa.Column("handoff_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("handoff_consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "user_id", sa.Uuid(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=True
        ),
        sa.Column("created_account", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "password_retired", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # UNIQUE, not merely indexed. These two constraints ARE the replay protection — a lookup plus an
    # application-level "have I seen this?" check loses the race between two concurrent callbacks.
    op.create_index("ix_oauth_transactions_state", "oauth_transactions", ["state"], unique=True)
    op.create_index(
        "ix_oauth_transactions_handoff_code",
        "oauth_transactions",
        ["handoff_code"],
        unique=True,
    )
    op.create_index("ix_oauth_transactions_guest_user_id", "oauth_transactions", ["guest_user_id"])
    op.create_index("ix_oauth_transactions_user_id", "oauth_transactions", ["user_id"])


def downgrade() -> None:
    op.drop_index("ix_oauth_transactions_user_id", table_name="oauth_transactions")
    op.drop_index("ix_oauth_transactions_guest_user_id", table_name="oauth_transactions")
    op.drop_index("ix_oauth_transactions_handoff_code", table_name="oauth_transactions")
    op.drop_index("ix_oauth_transactions_state", table_name="oauth_transactions")
    op.drop_table("oauth_transactions")
