"""cognition.video_item: the video round's content and its answer key

One clip, one subtly altered clip, and the three questions asked about them. The round occupies a
single Royale slot but produces THREE scored answers, so this table holds three correct indexes.

`questions` and `change_question` are JSONB rather than columns because the shape is authored
content, not schema: {prompt, options[4], correct_index}. A list for the comprehension pair means
the count can change without another migration.

**This table is the answer key.** Nothing in it may reach a client except prompts, options and the
asset ids; the correct indexes are resolved server-side per answer, exactly as trivia's are.

Hand-written, not autogenerated: autogenerate on this schema routinely proposes unrelated drops.

Reversible: downgrade drops the table. It holds ingested content that is rebuilt from
`<content_root>/video/manifest.json` by `run ingest-video`, so nothing is lost that the content
repo does not already hold.

Revision ID: d4e5f6a7b8c9
Revises: c3d4e5f6a7b8
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "d4e5f6a7b8c9"
down_revision = "c3d4e5f6a7b8"
branch_labels = None
depends_on = None

SCHEMA = "cognition"


def upgrade() -> None:
    op.create_table(
        "video_item",
        sa.Column("id", sa.Uuid(), primary_key=True, nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        # Asset IDS naming files in <content_root>/video/assets/ — never URLs, so the manifest and
        # its media travel together behind ROT_CONTENT_DIR.
        sa.Column("base_asset", sa.Text(), nullable=False),
        sa.Column("altered_asset", sa.Text(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "questions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "change_question",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("difficulty", sa.String(length=16), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        schema=SCHEMA,
    )
    # UNIQUE on key: the ingest upserts on it, so two rows sharing a key would make "which one did
    # today's Royale pin?" unanswerable.
    op.create_index("ix_video_item_key", "video_item", ["key"], unique=True, schema=SCHEMA)
    # The draw only ever selects active rows; index it so retiring content stays cheap.
    op.create_index("ix_video_item_active", "video_item", ["active"], schema=SCHEMA)

    # The round type the instances point at. Seeded here rather than by the ingest so a deployment
    # that has not ingested content yet still has a coherent schema.
    op.execute(
        sa.text(
            "INSERT INTO cognition.round_type (id, key, display_name, config, active) "
            "VALUES (gen_random_uuid(), 'video', 'Video', '{}'::jsonb, true) "
            "ON CONFLICT (key) DO NOTHING"
        )
    )


def downgrade() -> None:
    op.execute(sa.text("DELETE FROM cognition.round_type WHERE key = 'video'"))
    op.drop_index("ix_video_item_active", table_name="video_item", schema=SCHEMA)
    op.drop_index("ix_video_item_key", table_name="video_item", schema=SCHEMA)
    op.drop_table("video_item", schema=SCHEMA)
