"""user daily stats

Revision ID: d7947da0506d
Revises: cc33dd44ee55
Create Date: 2026-07-04 11:56:27.980060

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7947da0506d"
down_revision: str | Sequence[str] | None = "cc33dd44ee55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_daily_stats",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("stat_date", sa.Date(), nullable=False),
        sa.Column("answers", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("correct", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sum_time_frac", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("best_streak", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("hard_correct", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "per_category",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "stat_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_daily_stats")
    # ### end Alembic commands ###
