// Real lobby art — the dominant illustrated objects for the Home screen, replacing the coded SVG
// placeholders. The supplied PNGs in this folder ship with an opaque near-white background (which
// renders as a light box on the dark cards), so we import the background-removed copies under
// ./clean/ (generated by scripts/strip_bg.py via corner flood-fill; originals are left untouched).
// NOTE: these are large source files (~1.4 MB each); they are NOT in the PWA precache glob (png is
// excluded), so they load on demand rather than on install. A downscale/webp pass is the obvious
// follow-up if Home's first paint needs to be lighter on cellular.
import avatarBot from "./clean/avatar-bot.png";
import avatarHooded from "./clean/avatar-hooded.png";
import chestVault from "./clean/chest-vault.png";
import coin from "./clean/coin.png";
import crownArena from "./clean/crown-arena.png";
import crownCta from "./clean/crown-cta.png";
import crownHero from "./clean/crown-hero.png";
import rotRoyaleBanner from "./clean/rot-royale-banner.png";
import crownPodium from "./clean/crown-podium.png";
import gem from "./clean/gem.png";
import flagProgress from "./clean/flag-progress.png";
import flameStreak from "./clean/flame-streak.png";
import globeCampaign from "./clean/globe-campaign.png";
import shieldAvatar from "./clean/shield-avatar.png";
import shieldGoldIii from "./clean/shield-gold-iii.png";

export const lobbyArt = {
  crownHero,
  crownArena,
  crownCta,
  crownPodium,
  avatarHooded,
  avatarBot,
  coin,
  gem,
  chestVault,
  globeCampaign,
  shieldGoldIii,
  shieldAvatar,
  flameStreak,
  flagProgress,
  rotRoyaleBanner,
} as const;
